-include $($(TARGET)_DEPS)

#C
$($(TARGET)_PATH_BUILD_BIN)/%$($(TARGET)_BIN_EXT): TARGET:=$(TARGET)
$($(TARGET)_PATH_BUILD_BIN)/%$($(TARGET)_BIN_EXT): $(PATH_SRC)/%.c $(PATH_SRC)/%.h $($(TARGET)_OBJS) $(MAKEFILE_MONITOR)
	$($(TARGET)_C_CC) $($(TARGET)_C_FLAGS) $($(TARGET)_C_INCLUDES) -MMD -MP $< -o $@ -Wl,--start-group $($(TARGET)_OBJS) -Wl,--end-group $($(TARGET)_C_LFLAGS) $($(TARGET)_C_LIBS)

$($(TARGET)_PATH_BUILD_BIN)/%$($(TARGET)_BIN_EXT): TARGET:=$(TARGET)
$($(TARGET)_PATH_BUILD_BIN)/%$($(TARGET)_BIN_EXT): $(PATH_SRC)/%.c $($(TARGET)_OBJS) $(MAKEFILE_MONITOR)
	$($(TARGET)_C_CC) $($(TARGET)_C_FLAGS) $($(TARGET)_C_INCLUDES) -MMD -MP $< -o $@ -Wl,--start-group $($(TARGET)_OBJS) -Wl,--end-group $($(TARGET)_C_LFLAGS) $($(TARGET)_C_LIBS)

$($(TARGET)_PATH_BUILD_OBJS)/%$($(TARGET)_OBJ_EXT): TARGET:=$(TARGET)
$($(TARGET)_PATH_BUILD_OBJS)/%$($(TARGET)_OBJ_EXT): $(PATH_SRC)/%.c $(PATH_SRC)/%.h $(MAKEFILE_MONITOR)
	$($(TARGET)_C_CC) $($(TARGET)_C_FLAGS) -MMD -MP -c $< -o $@

$($(TARGET)_PATH_BUILD_OBJS)/%$($(TARGET)_OBJ_EXT): TARGET:=$(TARGET)
$($(TARGET)_PATH_BUILD_OBJS)/%$($(TARGET)_OBJ_EXT): $(PATH_SRC)/%.c $(MAKEFILE_MONITOR)
	$($(TARGET)_C_CC) $($(TARGET)_C_FLAGS) -MMD -MP -c $< -o $@
	
#C++
$($(TARGET)_PATH_BUILD_BIN)/%$($(TARGET)_BIN_EXT): TARGET:=$(TARGET)
$($(TARGET)_PATH_BUILD_BIN)/%$($(TARGET)_BIN_EXT): $(PATH_SRC)/%.cpp $(PATH_SRC)/%.h $($(TARGET)_OBJS) $(MAKEFILE_MONITOR)
	$($(TARGET)_CPP_CC) $($(TARGET)_CPP_FLAGS) $($(TARGET)_CPP_INCLUDES) -MMD -MP $< -o $@ -Wl,--start-group $($(TARGET)_OBJS) -Wl,--end-group $($(TARGET)_CPP_LFLAGS) $($(TARGET)_CPP_LIBS)

$($(TARGET)_PATH_BUILD_BIN)/%$($(TARGET)_BIN_EXT): TARGET:=$(TARGET)
$($(TARGET)_PATH_BUILD_BIN)/%$($(TARGET)_BIN_EXT): $(PATH_SRC)/%.cpp $($(TARGET)_OBJS) $(MAKEFILE_MONITOR)
	$($(TARGET)_CPP_CC) $($(TARGET)_CPP_FLAGS) $($(TARGET)_CPP_INCLUDES) -MMD -MP $< -o $@ -Wl,--start-group $($(TARGET)_OBJS) -Wl,--end-group $($(TARGET)_CPP_LFLAGS) $($(TARGET)_CPP_LIBS)

$($(TARGET)_PATH_BUILD_OBJS)/%$($(TARGET)_OBJ_EXT): TARGET:=$(TARGET)
$($(TARGET)_PATH_BUILD_OBJS)/%$($(TARGET)_OBJ_EXT): $(PATH_SRC)/%.cpp $(PATH_SRC)/%.h $(MAKEFILE_MONITOR)
	$($(TARGET)_CPP_CC) $($(TARGET)_CPP_FLAGS) -MMD -MP -c $< -o $@

$($(TARGET)_PATH_BUILD_OBJS)/%$($(TARGET)_OBJ_EXT): TARGET:=$(TARGET)
$($(TARGET)_PATH_BUILD_OBJS)/%$($(TARGET)_OBJ_EXT): $(PATH_SRC)/%.cpp $(MAKEFILE_MONITOR)
	$($(TARGET)_CPP_CC) $($(TARGET)_CPP_FLAGS) -MMD -MP -c $< -o $@

# DEBUG
ifeq ("$(findstring debug,$(MAKECMDGOALS))","debug")
$(info $$$(TARGET)_PATH_BUILD_OBJS is [${$(TARGET)_PATH_BUILD_OBJS}])
$(info $$PATHS_SRC_OBJS is [${PATHS_SRC_OBJS}])

$(info $$$(TARGET)_PATH_BUILD_BIN is [${$(TARGET)_PATH_BUILD_BIN}])
$(info $$PATHS_SRC_BIN is [${PATHS_SRC_BIN}])
$(info $$TARGET_BIN_EXT is [${TARGET_BIN_EXT}])
endif
# END DEBUG
